require 'nvim-treesitter.configs'.setup {
    ensure_installed = {
        "markdown",
        "c",
        "c_sharp",
        "cmake",
        "cpp",
        "rust",
        "lua",
        "vim",
--        "help",
        "query",
        "javascript",
        "typescript",
        "go",
        "java",
        "css",
        --	  "html",
        "diff",
        "gitcommit",
        --  "gitconfig",
        "git_rebase",
        "gitattributes",
        "gitignore",
        "http",
        "json",
    },
    sync_install = false,
    auto_install = true,
    autotag = {
        enable = true,
    },
    highlight = {
        enable = true,
        additional_vim_regex_highlighting = false,
    },
}
